function T = A4_HT36C_A_data()
    T = ETable('A4_HT36C_A.xlsx', ["NumTube", "T1", "T2", "T3", "T4", "T5",...
        "T6","T7","T8","T9","T10","HPump","FHot","CValve","FCold","Orient",...
        "Notes","H_SpecHeat","C_SpecHeat","HPoint","HTemp","CPoint","CTemp",...
        "DHot","HAvg","RhoH","HVisc","ReH","CAvg","RhoC","CVisc","ReC","HLoss",...
        "CGain","mdotH","mdotC","Qe","Qa","Qf","Eff","HEff","CEff","MeanEff","LMTD","U","Score",...
        "AvT1","AvT2","AvT3","AvT8","AvT9","AvT10","T6","T7","T8","T3","T4","T5"]);
    T.unitsList = ["",repmat("$$^{\circ}C$$",1:10),"%","$$^{L}/{min}$$","%",...
        "$$^{L}/{min}$$","","","","$$^{J}/_{kJ*K}$$","$$^{J}/_{kJ*K}$$","",...
        "$$^{\circ}C$$","","$$^{\circ}C$$","mm","$$^{\circ}C$$","$$^{kg}/_{m^{3}}$$",...
        "$$^{Pa*s}^$$","","$$^{\circ}C$$","$$^{kg}/_{m^{3}}$$","$$^{Pa*s}^$$","",...
        "$$^{\circ}C$$","$$^{kg}/_{m^{3}}$$","$$^{\circ}C$$","$$^{\circ}C$$",...
        "$$^{kg}/{s}$$","$$^{kg}/{s}$$","W","W","W",repmat("%",1:4),"","",""...
        "%",repmat("$$^{\circ}C$$",1:6),repmat("$$^{\circ}C$$",1:6)];
        
    %Convert Units for Pa*s
end