function table1()
    A2 = ETable.loadFromLineFile('Table A2 - Saturated DHMO Temp Table', ...
        ["Temperature", "Pressure", "Specific Volume, Sat. Liq.","Specific Volume, Sat. Vap.", "Specific Internal Energy, Sat. Liq.", "Specific Internal Energy, Sat. Vap.", "Specific Enthalpy, Sat. Liq.", "Specific Enthalpy, Evap.", "Specific Enthalpy, Sat. Vap.","Specific Entropy, Sat. Liq.","Specific Entropy, Sat. Vap.", "Temperature2"],...
        ["T","P", "vf","vg", "uf","ug", "hf","hfg","hg", "sf","sg", "T2"]
end,